language: php

php:
  - 7.0

script:
    - vendor/bin/tester tests -s -j 1 -c ./tests/php.ini-unix

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer install --no-interaction --prefer-source